Revert previous commit as it broke builds under some conditions.
The following errors appeared on Ubuntu builds:

cc1: warning: command line option '-ftemplate-depth=300' is valid for C++/ObjC++ but not for C [enabled by default]
In file included from store.h:9:0,
                 from store.c:21:
render_config.h:6:1: error: expected identifier or '(' before '/' token
render_config.h:15:1: error: stray '#' in program
...

As I don't know why this broke, or how to fix it, I am reverting this patch for now. It also only triggeres after a make distclean